// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2dNijmBT6eRLE46OaUgq8BsjWE1fFJg',
    appId: '1:293380949381:web:1249ef753e1a5579f3b0ec',
    messagingSenderId: '293380949381',
    projectId: 'un-nabawi-masjid-app',
    authDomain: 'un-nabawi-masjid-app.firebaseapp.com',
    storageBucket: 'un-nabawi-masjid-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-qOZwh-UDLqCUgC7j92TePwQHnWY4tw',
    appId: '1:293380949381:android:387bb5b2b960032df3b0ec',
    messagingSenderId: '293380949381',
    projectId: 'un-nabawi-masjid-app',
    storageBucket: 'un-nabawi-masjid-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb3_AkTeUkUFb5JoLHyXv5ca_aX8jZ1dw',
    appId: '1:293380949381:ios:3b9ccf8377174d52f3b0ec',
    messagingSenderId: '293380949381',
    projectId: 'un-nabawi-masjid-app',
    storageBucket: 'un-nabawi-masjid-app.firebasestorage.app',
    iosClientId: '293380949381-jki1bac4akph5474la8d24lkav9li43u.apps.googleusercontent.com',
    iosBundleId: 'com.example.unNabawiMasjidAppClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb3_AkTeUkUFb5JoLHyXv5ca_aX8jZ1dw',
    appId: '1:293380949381:ios:3b9ccf8377174d52f3b0ec',
    messagingSenderId: '293380949381',
    projectId: 'un-nabawi-masjid-app',
    storageBucket: 'un-nabawi-masjid-app.firebasestorage.app',
    iosClientId: '293380949381-jki1bac4akph5474la8d24lkav9li43u.apps.googleusercontent.com',
    iosBundleId: 'com.example.unNabawiMasjidAppClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2dNijmBT6eRLE46OaUgq8BsjWE1fFJg',
    appId: '1:293380949381:web:2f866b90d3707af3f3b0ec',
    messagingSenderId: '293380949381',
    projectId: 'un-nabawi-masjid-app',
    authDomain: 'un-nabawi-masjid-app.firebaseapp.com',
    storageBucket: 'un-nabawi-masjid-app.firebasestorage.app',
  );
}
